// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvzowkgjudxkiebyzxfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2em93a2dqdWR4a2llYnl6eGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTUzNDMsImV4cCI6MjA3MjU5MTM0M30.T13hIDUONDvtjZqlAZvVV2X6zaq301ph2RwePp4VyJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});